### ISSUE TITLE
Support IE11

### ISSUE THREAD

**Issue by meowhunter** [mljs/array#8]
Dist fails in ie11 cause of default argument value here:  https://github.com/mljs/array/blob/master/packages/array-rescale/src/index.js#L5

Could you please compile to proper es2015 module
Rollup es2015 guide: https://github.com/rollup/rollup/wiki/pkg.module#wait-it-just-means-import-and-export--not-other-future-javascript-features

**Comment by stropitek** [comment]
Hello @meowhunter 

The problem rollup is pointing at is transpiling es6 features (like arrow functions) to es5 vanilla javascript, not transforming es6 modules to commonJS or UMD.

A bundler like webpack will handle all your dependencies that use es6 module without any special configuration needed.

**Comment by glebmachine** [comment]
Yeah, that's why Rollup recommends to have additional bundles:
```
  "main": "dist/my-package.umd.js",
  "module": "dist/my-package.esm.js"
```

UMD for with transpiled to es5 code, that's not need to be compiled.
ESM module, more clean code, needs to be compiled over.

For example, modern approach for compiled code distribution is to have multiple compiled distribs, suited for most cases. So in Angular  ecosystem we have following example:

`package.json` from  `@angular/core`
```
  "module": "./fesm5/core.js",
  "es2015": "./fesm2015/core.js",
  "esm5": "./esm5/core.js",
  "esm2015": "./esm2015/core.js",
  "fesm5": "./fesm5/core.js",
  "fesm2015": "./fesm2015/core.js",
```

This approach allow to reduce compilation time, and maximum fit for most bundlers and loaders (from SystemJs up to bazel)

Unfortunately `angular-cli` strictly disallow to recompile 3rd party libraries. 
So, we unable to use non-production ready 3-rd party libs (this is common mistake in published dists)

If you don't mind, we will add additional outputs and made PR?

**Comment by glebmachine** [comment]
@stropitek waiting your approval, i'm added proper transpilation
This add support for IE11, and Chrome <49
